### ISSUE TITLE
Dynamic ssh_tunnelling doesn't work on windows

### ISSUE THREAD

**Issue by mrthevinh** [Red-M/RedSSH#3]
I run ssh_tunnel.py (examples) on window 10:
`"Failed to establish a new connection: %s" % error
urllib3.exceptions.NewConnectionError: <urllib3.contrib.socks.SOCKSConnection object at 0x000001F45668A630>: Failed to establish a new connection: [WinError 10054] An existing connection was forcibly closed by the remote host`

**Comment by Red-M** [comment]
I don't test or release for windows due a number of reasons, however this looks to be an exclusively windows issue after a google search of `WinError 10054`. All I am able to gleam from this is network instability from the windows machine as this particular error is fairly generic, ranging from disagreement in handshake to a host being unavailable.

**Comment by mrthevinh** [comment]
I run redssh on 3.8 and got erro!
It' work great with python 3.7 now! Thank you for create redssh I love it so much!

**Comment by Red-M** [comment]
I'd ask that you test if the remote server can access the resource you're asking for.
It sounds like you're trying to access something that the remote end can't get to.
I also can't assist much with Windows as I don't test for or run any validation for Windows.
