### ISSUE TITLE
Dynamic ssh_tunnelling sock5 doesn't work with the browser firefox and chrome

### ISSUE THREAD

**Issue by mrthevinh** [Red-M/RedSSH#4]
Sock5 create by redssh working with requests but doesn't work with my browser firefox and chrome!

**Comment by Red-M** [comment]
I need to know a little more about what environment you're running this in.
Is this on Linux or another platform? I only test and validate the library for Linux.

**Comment by mrthevinh** [comment]
I test on windows 10 and I will check on linux like ubuntu
