### ISSUE TITLE
`RedSSH()` `known_hosts` keyword argument missing documentation.

### ISSUE THREAD

**Issue by brendan-simon-indt** [Red-M/RedSSH#7]
The `known_hosts` keyword argument does not have a description in the parameters section of the documentation.

https://redssh.readthedocs.io/en/latest/redssh.html

```python
class redssh.RedSSH(encoding='utf8', terminal='vt100', known_hosts=None, ssh_host_key_verification=<SSHHostKeyVerify.warn: 1>, ssh_keepalive_interval=0.0, set_flags={}, method_preferences={}, callbacks={}, auto_terminate_tunnels=False, tcp_nodelay=False)
```

**Comment by Red-M** [comment]
Thanks for noticing that, I have a major refactor in the works on develop that needs some further work so fixing this might take a while.

**Comment by Red-M** [comment]
This should be fixed when rtd builds the latest docs.
