### ISSUE TITLE
execute_commands throws exception

### ISSUE THREAD

**Issue by atauzki** [Red-M/RedSSH#8]
redexpect version:
redlibssh                             2.0.9
redlibssh2                           2.1.5.post1
redssh                                  3.0.0

python: 3.9.16 conda enviornment on Ubuntu 18.04
this is screenshot:

![image](https://user-images.githubusercontent.com/19769843/219543825-d97482c0-c705-47d2-bd1b-7cae0cd702dc.png)

**Comment by Red-M** [comment]
I've fixed this and I'm currently working on getting some proper tests to make sure this doesn't regress.
In the meantime, RedExpect should be able to do what you're looking for.

**Comment by Red-M** [comment]
Fixed in [fc789cf](https://github.com/Red-M/RedSSH/commit/fc789cf4994ccd0499d86fe554187d6af8c6d5e5)
